title: Statistics of Common Crawl Monthly Archives
description: Number of pages, distribution of top-level domains, crawl overlaps, etc. - basic metrics about Common Crawl Monthly Crawl Archives
latest_crawl: CC-MAIN-2021-21

show_navigation: True
navlist:
 - title: Home
   url: 
 - title: Size of crawls
   url: /plots/crawlsize
 - title: Top-level domains
   url: /plots/tlds
 - title: Registered domains
   url: /plots/domains
 - title: Crawler metrics
   url: /plots/crawlermetrics
 - title: Crawl overlaps
   url: /plots/crawloverlap
 - title: Media types
   url: /plots/mimetypes
 - title: Character sets
   url: /plots/charsets
 - title: Languages
   url: /plots/languages

theme: jekyll-theme-minimal
